use_gpu: true

data:
    speakers: ["CF02", "CF03", "CF04", "CF05", "CM01", "CM04", "CM05", "CM06", "CM08", "CM09", "CM10", "CM12", "CM13", "F02", "F03", "F04", "F05", "M01", "M04","M05", "M07", "M08", "M09", "M10", "M11", "M12", "M14", "M16"]
    sr: 16000
    shift_ms: 10
    fftl: 1024
    num_mels: 80
    hop_length: 160
    top_db: 120
    PAD_token: PAD
    SOS_token: SOS
    EOS_token: EOS
    train_test_frac: 0.9
    ignore_speakers: ["F02", "F03", "M01", "M04", "M07", "M12", "M16"]

directories:
    root: ../datasets/UASPEECH/audio/
    speakers: speakers/
    noise_removed: noise_removed/
    silence_removed: silence_removed/
    features: features/
    exps: exps/

model:
    name: BLSTM
    hidden_size: 200
    num_layers: 4
    bidirectional: true
    num_linear_layers: 2
    batch_first: true
    dropout: 0.1
    lr: 0.0001
    embed_dim: 300

train:
    log_step: 20
    model_save_step: 5000
    num_epochs: 50000
    batch_size: 16
    class_history: 50
    regular_epochs: 50000
    fairness_lambda: 0


